BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "accounts" (
	"account"	TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	PRIMARY KEY("account")
);
CREATE TABLE IF NOT EXISTS "articles" (
	"id"	INTEGER NOT NULL,
	"account"	TEXT NOT NULL,
	"words"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "comments" (
	"id"	INTEGER NOT NULL,
	"account"	TEXT NOT NULL,
	"words"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
